"""init

Revision ID: 7943cb25c337
Revises: 
Create Date: 2026-06-07 13:15:45.489836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7943cb25c337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_reviewer_id'), 'applications', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_applications_scholarship_id'), 'applications', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.drop_column('applications', 'student_name')
    op.drop_column('applications', 'scholarship_title')
    op.drop_column('reviewer_requests', 'reviewer_name')
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('students', 'student_name')
    op.add_column('users', sa.Column('verified_email', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET verified_email = false WHERE verified_email IS NULL')
    op.alter_column('users', 'verified_email', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_email')
    op.add_column('students', sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('reviewer_requests', sa.Column('reviewer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('scholarship_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_scholarship_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_reviewer_id'), table_name='applications')
    # ### end Alembic commands ###
